import type { Metadata } from "next";
import {  Encode_Sans } from "next/font/google";
import "./globals.css";


const encodeSans = Encode_Sans({
  variable: "--font-encode-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${encodeSans.variable}antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
